version: '3.8'
services:

  dev:
    image: ruby:3.3
    build:
      context: .
      dockerfile: dev/Dockerfile.dev
    volumes:
      - .:/home/loco_motion
    tty: true
    stdin_open: true

  yard:
    build:
      context: .
      dockerfile: dev/Dockerfile.yard
    volumes:
      - .:/home/loco_motion
    ports:
      - 8808:8808
    tty: true
    stdin_open: true
