services:

  dev:
    build:
      context: .
      dockerfile: dev/Dockerfile.dev
    volumes:
      - .:/home/loco_motion
    tty: true
    stdin_open: true

  loco:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - path: docs/demo/.env.local
        required: false
    volumes:
      - .:/home/loco_motion
    tty: true
    stdin_open: true

  demo:
    build:
      context: docs/demo
      dockerfile: Dockerfile.demo
    env_file:
      - path: docs/demo/.env.local
        required: false
    volumes:
      - ./docs/demo:/home/loco_demo
      - .:/home/loco_demo/vendor/loco_motion-rails
      - .:/home/loco_motion
    ports:
      - 3000:3000
    tty: true
    stdin_open: true

  yard:
    build:
      context: .
      dockerfile: docs/yard/Dockerfile.yard
    volumes:
      - .:/home/loco_motion
    ports:
      - 8808:8808
    tty: true
    stdin_open: true
