FROM ruby:3.3

RUN apt-get update -qq && apt-get install -y build-essential git
RUN gem update --system

ENV APP_HOME /home/loco-motion

WORKDIR $APP_HOME

COPY Gemfile Gemfile.* loco-motion.gemspec $APP_HOME

RUN bundle install

ENTRYPOINT [ "bin/start-yard.sh" ]
