FROM ruby:3.3.5

RUN apt-get update -qq && apt-get install -y build-essential git tini vim
RUN gem update --system

ENV APP_HOME /home/loco_motion

WORKDIR $APP_HOME

COPY Gemfile Gemfile.* loco_motion.gemspec .yardopts $APP_HOME

RUN bundle install

ENTRYPOINT [ "/usr/bin/tini", "--", "docs/yard/bin/start-yard.sh" ]
