services:

  db:
    image: postgres:15-bullseye
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data

  dev:
    build: ./dev/
    volumes:
      - .:/home/app
    tty: true
    stdin_open: true

  # app:
  #   build: .
  #   volumes:
  #     - .:/home/app
  #   ports:
  #     - 3000:3000
  #   tty: true
  #   stdin_open: true
  #   depends_on:
  #     - db

volumes:
  postgres:
