services:

  db:
    image: postgres:15-bullseye
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    command: redis-server
    volumes:
      - 'redis:/data'

  dev:
    image: timbru31/ruby-node:3.3-slim-18
    build: ./dev/
    volumes:
      - .:/home/app
    tty: true
    stdin_open: true

  # app:
  #   build: .
  #   volumes:
  #     - .:/home/app
  #   ports:
  #     - 3000:3000
  #   tty: true
  #   stdin_open: true
  #   depends_on:
  #     - db
  #     - redis

volumes:
  postgres:
  redis:
