name: Publish Yard Docs

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version_name:
        type: string
        required: false
        description: 'The new version / directory to be created'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Generate Docs
        run: bundle exec yard

      - name: List Files
        run: ls -la ./docs/yard/generated

      - name: "📂 Deploy Generated to SiteGround"
        uses: milanmk/actions-file-deployer@master
        with:
          artifacts: true
          remote-protocol: "ftp"
          remote-port: 21
          remote-host: ${{ secrets.SITEGROUND_FTP_HOST }}
          remote-user: ${{ secrets.SITEGROUND_FTP_USERNAME }}
          remote-password: ${{ secrets.SITEGROUND_FTP_PASSWORD }}
          local-path: "./docs/yard/generated/"
          remote-path: "/loco-motion-docs.profoundry.us/public_html/${{ github.event.inputs.version_name || github.event.release.tag_name || github.sha }}/"

      - name: "📂 Deploy Assets to SiteGround"
        uses: milanmk/actions-file-deployer@master
        with:
          artifacts: true
          remote-protocol: "ftp"
          remote-port: 21
          remote-host: ${{ secrets.SITEGROUND_FTP_HOST }}
          remote-user: ${{ secrets.SITEGROUND_FTP_USERNAME }}
          remote-password: ${{ secrets.SITEGROUND_FTP_PASSWORD }}
          local-path: "./docs/assets/"
          remote-path: "/loco-motion-docs.profoundry.us/public_html/${{ github.event.inputs.version_name || github.event.release.tag_name || github.sha }}/docs/assets"
